//! interp-closure removal Stage 3: the committed compiler-island dump
//! (`src/compiler_island.typld`) must stay in sync with `compiler.rs`'s
//! `SOURCE`. It is generated by `scripts/regen-compiler-island.sh` (the
//! `typl-bootstrap-island` binary) and consumed at startup by
//! `compiler::load_aot` (Stage 4).
//!
//! Two guards, at two granularities:
//!
//! * [`island_artifacts_are_fresh`] compares the digest recorded in the dump
//!   against a fresh digest of `SOURCE`. Cheap, and the same check `load_aot`
//!   makes at startup — but it only covers one of the artifact's two inputs.
//! * [`the_committed_island_matches_a_fresh_build`] rebuilds the dump and
//!   compares the bytes. Slower, and covers both inputs, because the output
//!   is downstream of everything the output depends on.

use typelisp::compile::bootstrap::build_island_artifact;
use typelisp::compile::llvm_context;
use typelisp::compiler;
use typelisp::dump::{parse, read_state, source_digest};

use inkwell::memory_buffer::MemoryBuffer;
use inkwell::module::Module;

const DUMP: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/src/compiler_island.typld");
const REGEN: &str = "run scripts/regen-compiler-island.sh";

fn committed() -> Vec<u8> {
    std::fs::read(DUMP).unwrap_or_else(|e| panic!("{} unreadable ({}) — {}", DUMP, e, REGEN))
}

#[test]
fn island_artifacts_are_fresh() {
    let bytes = committed();
    let units = parse(&bytes, "compiler island").unwrap_or_else(|e| panic!("{} — {}", e, REGEN));
    let unit = units.first().unwrap_or_else(|| panic!("the island dump holds no units — {}", REGEN));
    let state = read_state(unit.types, "compiler island").unwrap_or_else(|e| panic!("{} — {}", e, REGEN));
    assert_eq!(
        state.source_digest,
        Some(source_digest(compiler::SOURCE)),
        "the island dump is stale relative to compiler.rs's SOURCE — {}",
        REGEN
    );

    let _guard = typelisp::compile::COMPILE_LOCK.lock().unwrap();
    let buffer = MemoryBuffer::create_from_memory_range_copy(unit.bitcode, "island");
    Module::parse_bitcode_from_buffer(&buffer, llvm_context())
        .unwrap_or_else(|_| panic!("the island dump's bitcode failed to parse — {}", REGEN));
}

/// The committed bitcode must be what building it *now* produces.
///
/// The hash above answers "does the artifact match `SOURCE`", which is only
/// half the question: the bitcode is `SOURCE` **as compiled by the Rust-side
/// LLVM builders** (`eval_llvm_builtin_method`), so editing a builder changes
/// the artifact with `SOURCE` untouched. That went undetected once already —
/// Stage D replaced the emitted indirect-apply sequence
/// (`rt_closure_fnptr` + an env loop + an indirect call) with a single
/// `rt_apply_any` call, and the committed island kept carrying the old one
/// until something unrelated forced a regeneration.
///
/// Comparing the *output* covers both inputs at once and needs no guess about
/// which parts of the compiler matter: anything that changes the emitted IR
/// changes these bytes, and anything that doesn't, doesn't. Hashing the
/// compiler binary instead would have the opposite problem — every unrelated
/// Rust edit would demand a regeneration, and a guard that cries wolf on every
/// commit is one people learn to ignore.
///
/// This is sound only because regeneration is a **fixpoint**: the build
/// installs the committed `.bc` and drives *its* native `compile-function`
/// (the snapshot chain), so the artifact is an input to its own construction.
/// It converges because what gets emitted is decided by `SOURCE`'s logic and
/// the Rust builders, not by which generation is driving — verified by
/// regenerating twice from different generations and getting identical bytes.
///
/// **But it can take two passes to get there.** When a change alters what the
/// island *emits*, the first regeneration compiles the new `SOURCE` with the
/// previous generation, so the result still carries the old shape and this test
/// fails on it; a second pass, now driven by the new island, converges. So if
/// this fails immediately after a regeneration, run the script again before
/// hunting for the difference. 2026-08-16: reordering `compile-break`'s `store`
/// and its `rt_truncate_sexpr_roots` call left exactly the island's own two
/// `break` sites in the old order — 4568 bytes of difference for 24 lines of
/// IR.
///
/// A caveat for anyone seeing this fail with no local change: bitcode encoding
/// is LLVM-version-specific, so a different LLVM 17 patch release can produce
/// different bytes. That is not a false alarm — it means the committed
/// artifact really was built by a different compiler than the one in hand.
#[test]
fn the_committed_island_matches_a_fresh_build() {
    let committed = committed();

    // The build walks `compile-function`'s huge `labels` body, which needs far
    // more stack than a libtest thread has — the same 64MB the bootstrap
    // binary gives it (`src/bin/bootstrap_island.rs`).
    let fresh = std::thread::Builder::new()
        .stack_size(64 * 1024 * 1024)
        .spawn(|| build_island_artifact().expect("building the island dump failed"))
        .expect("failed to spawn the island build thread")
        .join()
        .expect("the island build thread panicked");

    if fresh != committed {
        // Never `assert_eq!` two megabyte-sized `Vec<u8>`s — say where they
        // part instead.
        let at = fresh.iter().zip(&committed).position(|(a, b)| a != b);
        panic!(
            "src/compiler_island.typld is not what building it now produces — run \
             scripts/regen-compiler-island.sh (committed {} bytes, fresh {} bytes, \
             first difference at {}). If you just ran it, run it again — a change to \
             what the island emits needs a second pass to reach the fixpoint. If \
             SOURCE is unchanged, an `llvm-*` builder changed the emitted IR.",
            committed.len(),
            fresh.len(),
            match at {
                Some(i) => i.to_string(),
                None => "the end — one is a prefix of the other".to_string(),
            }
        );
    }
}

/// The committed artifact is bitcode **plus one trailing NUL byte**, and that
/// byte is load-bearing.
///
/// inkwell's `MemoryBuffer::as_slice` deliberately includes the terminator LLVM
/// guarantees past the end of the buffer (`get_size` is `LLVMGetBufferSize()
/// + 1`), so that the slice can be handed straight back to
/// `MemoryBuffer::create_from_memory_range_copy` — which is exactly what
/// `Interp::install_compiled_library` does. That loader *asserts* the last byte
/// is NUL and then passes `len - 1` as the real size. Writer and reader are a
/// pair; the file on disk is in the form the reader demands.
///
/// The trap this guards is "4n+1 is odd, let me trim it": `llvm-dis` and
/// `llvm-bcanalyzer` both reject the file as written (the latter says why —
/// "Bitcode stream should be a multiple of 4 bytes in length"), which invites
/// exactly that cleanup. Trimming would not even trip the loader's own assert,
/// because the bitstream's last byte is padding zero too — LLVM would just get
/// a buffer one byte short, and fail somewhere less obvious.
///
/// Hence the length check rather than only the NUL check: after a trim the file
/// still *ends* with a zero, but `len - 1` stops being a multiple of 4. The
/// same assertion fires if an inkwell upgrade stops appending the terminator,
/// in which case the loader's pairing has to be revisited, not the artifact.
/// **`ISLAND_DUMP_BODY_ABI` says what the committed bytes are, so it must.**
///
/// The constant is hand-written because `build_island_artifact` installs the
/// committed bitcode without reading its checked state — that half is one
/// generation stale by construction — and bitcode does not record what ABI it
/// was built under. Calling a body under the wrong one is a wrong answer, not
/// an error anyone would see, so the claim gets a guard rather than trust.
#[test]
fn the_committed_islands_recorded_abi_matches_the_constant() {
    let units = parse(compiler::ISLAND_DUMP, "compiler island").expect("the committed island dump parses");
    let unit = units.first().expect("the committed dump holds a unit");
    let state = read_state(unit.types, "compiler island").expect("its state reads");
    assert_eq!(
        state.body_abi,
        compiler::ISLAND_DUMP_BODY_ABI,
        "src/compiler.rs's ISLAND_DUMP_BODY_ABI disagrees with what src/compiler_island.typld records"
    );
    assert_eq!(
        state.emits_abi,
        compiler::ISLAND_DUMP_EMITS_ABI,
        "src/compiler.rs's ISLAND_DUMP_EMITS_ABI disagrees with what src/compiler_island.typld records. \
         This is the constant everything this process compiles answers to (compile::EMITTED_BODY_ABI), \
         so a stale value here is a whole binary emitting one ABI and calling it another."
    );
}

#[test]
fn the_committed_island_keeps_its_trailing_nul() {
    let bytes = committed();
    let units = parse(&bytes, "compiler island").unwrap_or_else(|e| panic!("{} — {}", e, REGEN));
    let bc = units.first().expect("the island dump holds no units").bitcode;

    assert_eq!(&bc[..4], b"BC\xc0\xde", "the island dump's bitcode section is not LLVM bitcode at all");
    assert_eq!(
        bc.last().copied(),
        Some(0),
        "the island bitcode lost its trailing NUL — install_compiled_library \
         asserts on it (see src/compile/bootstrap.rs's write site)"
    );
    assert_eq!(
        (bc.len() - 1) % 4,
        0,
        "the island bitcode section is {} bytes; the bitstream proper must be a multiple of 4 \
         with exactly one NUL after it. If someone trimmed the terminator to please \
         llvm-dis, put it back — see src/compile/bootstrap.rs's write site.",
        bc.len()
    );
}
