//! interp-closure removal Stage 3: the committed compiler-island artifact
//! (`src/compiler_island.bc`) must stay in sync with `compiler.rs`'s
//! `SOURCE`. It is generated by `scripts/regen-compiler-island.sh` (the
//! `typl-bootstrap-island` binary) and consumed at runtime by
//! `compiler::load_aot` (Stage 4).
//!
//! Two guards, at two granularities:
//!
//! * [`island_artifacts_are_fresh`] compares the source hash embedded in the
//!   bitcode against a fresh hash of `SOURCE`. Cheap, and the same check
//!   `install_island_bitcode` makes at load time — but it only covers one of
//!   the artifact's two inputs.
//! * [`the_committed_island_matches_a_fresh_build`] rebuilds the bitcode and
//!   compares the bytes. Slower, and covers both inputs, because the output
//!   is downstream of everything the output depends on.

use typelisp::compile::bootstrap::{build_island_bitcode, island_source_hash, read_embedded_source_hash};
use typelisp::compile::llvm_context;
use typelisp::compiler;

use inkwell::memory_buffer::MemoryBuffer;
use inkwell::module::Module;

#[test]
fn island_artifacts_are_fresh() {
    let bc = std::fs::read(concat!(env!("CARGO_MANIFEST_DIR"), "/src/compiler_island.bc"))
        .expect("src/compiler_island.bc missing — run scripts/regen-compiler-island.sh");
    let _guard = typelisp::compile::COMPILE_LOCK.lock().unwrap();
    let buffer = MemoryBuffer::create_from_memory_range_copy(&bc, "island");
    let module = Module::parse_bitcode_from_buffer(&buffer, llvm_context())
        .expect("src/compiler_island.bc failed to parse — run scripts/regen-compiler-island.sh");
    let embedded = read_embedded_source_hash(&module, typelisp::compile::bootstrap::SOURCE_HASH_GLOBAL)
        .expect("src/compiler_island.bc has no embedded source hash — run scripts/regen-compiler-island.sh");
    assert_eq!(
        embedded,
        island_source_hash(compiler::SOURCE).expect("hashing SOURCE failed"),
        "compiler_island.bc is stale relative to compiler.rs's SOURCE — run scripts/regen-compiler-island.sh"
    );
}

/// The committed bitcode must be what building it *now* produces.
///
/// The hash above answers "does the artifact match `SOURCE`", which is only
/// half the question: the bitcode is `SOURCE` **as compiled by the Rust-side
/// LLVM builders** (`eval_llvm_builtin_method`), so editing a builder changes
/// the artifact with `SOURCE` untouched. That went undetected once already —
/// Stage D replaced the emitted indirect-apply sequence
/// (`rt_closure_fnptr` + an env loop + an indirect call) with a single
/// `rt_apply_any` call, and the committed island kept carrying the old one
/// until something unrelated forced a regeneration.
///
/// Comparing the *output* covers both inputs at once and needs no guess about
/// which parts of the compiler matter: anything that changes the emitted IR
/// changes these bytes, and anything that doesn't, doesn't. Hashing the
/// compiler binary instead would have the opposite problem — every unrelated
/// Rust edit would demand a regeneration, and a guard that cries wolf on every
/// commit is one people learn to ignore.
///
/// This is sound only because regeneration is a **fixpoint**: the build
/// installs the committed `.bc` and drives *its* native `compile-function`
/// (the snapshot chain), so the artifact is an input to its own construction.
/// It converges because what gets emitted is decided by `SOURCE`'s logic and
/// the Rust builders, not by which generation is driving — verified by
/// regenerating twice from different generations and getting identical bytes.
///
/// A caveat for anyone seeing this fail with no local change: bitcode encoding
/// is LLVM-version-specific, so a different LLVM 17 patch release can produce
/// different bytes. That is not a false alarm — it means the committed
/// artifact really was built by a different compiler than the one in hand.
#[test]
fn the_committed_island_matches_a_fresh_build() {
    let committed = std::fs::read(concat!(env!("CARGO_MANIFEST_DIR"), "/src/compiler_island.bc"))
        .expect("src/compiler_island.bc missing — run scripts/regen-compiler-island.sh");

    // The build walks `compile-function`'s huge `labels` body, which needs far
    // more stack than a libtest thread has — the same 64MB the bootstrap
    // binary gives it (`src/bin/bootstrap_island.rs`).
    let fresh = std::thread::Builder::new()
        .stack_size(64 * 1024 * 1024)
        .spawn(|| build_island_bitcode().expect("building the island bitcode failed"))
        .expect("failed to spawn the island build thread")
        .join()
        .expect("the island build thread panicked");

    if fresh != committed {
        // Never `assert_eq!` two megabyte-sized `Vec<u8>`s — say where they
        // part instead.
        let at = fresh.iter().zip(&committed).position(|(a, b)| a != b);
        panic!(
            "src/compiler_island.bc is not what building it now produces — run \
             scripts/regen-compiler-island.sh (committed {} bytes, fresh {} bytes, \
             first difference at {}). If SOURCE is unchanged, an `llvm-*` builder \
             changed the emitted IR.",
            committed.len(),
            fresh.len(),
            match at {
                Some(i) => i.to_string(),
                None => "the end — one is a prefix of the other".to_string(),
            }
        );
    }
}
