//! interp-closure removal Stage 3: the committed compiler-island artifact
//! (`src/compiler_island.bc`) must stay in sync with `compiler.rs`'s
//! `SOURCE`. It is generated by `scripts/regen-compiler-island.sh` (the
//! `typl-bootstrap-island` binary) and consumed at runtime by
//! `compiler::load_aot` (Stage 4). This guard fails whenever the source has
//! changed but the artifact wasn't regenerated — comparing the source hash
//! embedded in the bitcode (a `__typelisp_island_source_hash` global)
//! against a fresh hash of the current `SOURCE`.

use typelisp::compile::bootstrap::{island_source_hash, read_embedded_source_hash};
use typelisp::compile::llvm_context;
use typelisp::compiler;

use inkwell::memory_buffer::MemoryBuffer;
use inkwell::module::Module;

#[test]
fn island_artifacts_are_fresh() {
    let bc = std::fs::read(concat!(env!("CARGO_MANIFEST_DIR"), "/src/compiler_island.bc"))
        .expect("src/compiler_island.bc missing — run scripts/regen-compiler-island.sh");
    let _guard = typelisp::compile::COMPILE_LOCK.lock().unwrap();
    let buffer = MemoryBuffer::create_from_memory_range_copy(&bc, "island");
    let module = Module::parse_bitcode_from_buffer(&buffer, llvm_context())
        .expect("src/compiler_island.bc failed to parse — run scripts/regen-compiler-island.sh");
    let embedded = read_embedded_source_hash(&module)
        .expect("src/compiler_island.bc has no embedded source hash — run scripts/regen-compiler-island.sh");
    assert_eq!(
        embedded,
        island_source_hash(compiler::SOURCE).expect("hashing SOURCE failed"),
        "compiler_island.bc is stale relative to compiler.rs's SOURCE — run scripts/regen-compiler-island.sh"
    );
}
