//! The committed precompiled-prelude artifact (`src/prelude_compiled.bc`) must
//! stay in sync with `prelude.rs`'s `SOURCE`. It is generated by
//! `scripts/regen-prelude-bitcode.sh` (the `typl-bootstrap-prelude` binary) and
//! consumed at runtime by `prelude::load`.
//!
//! The same two guards, at the same two granularities, as
//! `island_artifacts_test.rs` — see that module's doc comment for why one is
//! not enough. The second matters more here: the prelude is compiled *by* the
//! compiler island, so this artifact goes stale when the island changes, and
//! the hash below covers only `prelude.rs`.

use typelisp::compile::bootstrap::{island_source_hash, read_embedded_source_hash};
use typelisp::compile::llvm_context;
use typelisp::compile::prelude_bootstrap::{build_prelude_bitcode, PRELUDE_SOURCE_HASH_GLOBAL};

use inkwell::memory_buffer::MemoryBuffer;
use inkwell::module::Module;

const REGEN: &str = "run scripts/regen-prelude-bitcode.sh";

#[test]
fn prelude_artifacts_are_fresh() {
    let bc = std::fs::read(concat!(env!("CARGO_MANIFEST_DIR"), "/src/prelude_compiled.bc"))
        .unwrap_or_else(|e| panic!("src/prelude_compiled.bc unreadable ({}) — {}", e, REGEN));
    let _guard = typelisp::compile::COMPILE_LOCK.lock().unwrap();
    let buffer = MemoryBuffer::create_from_memory_range_copy(&bc, "prelude");
    let module = Module::parse_bitcode_from_buffer(&buffer, llvm_context())
        .unwrap_or_else(|_| panic!("src/prelude_compiled.bc failed to parse — {}", REGEN));
    let embedded = read_embedded_source_hash(&module, PRELUDE_SOURCE_HASH_GLOBAL)
        .unwrap_or_else(|| panic!("src/prelude_compiled.bc has no embedded source hash — {}", REGEN));
    assert_eq!(
        embedded,
        island_source_hash(typelisp::prelude::SOURCE).expect("hashing SOURCE failed"),
        "prelude_compiled.bc is stale relative to prelude.rs's SOURCE — {}",
        REGEN
    );
}

/// The committed bitcode must be what building it *now* produces.
///
/// This is the guard that catches an island change: the prelude's bodies are
/// translated by `compiler.rs`'s `SOURCE` as compiled into
/// `src/compiler_island.bc`, plus the Rust-side LLVM builders — none of which
/// the hash above looks at. Comparing the output covers every input at once
/// without having to enumerate them.
///
/// Sound because the build is deterministic in the inputs and reads nothing
/// downstream of itself: unlike the island's generator, this one loads the
/// prelude *interpreted* and never installs the artifact it is replacing, so
/// building from the committed bytes and building from scratch are the same
/// computation.
#[test]
fn the_committed_prelude_matches_a_fresh_build() {
    let committed = std::fs::read(concat!(env!("CARGO_MANIFEST_DIR"), "/src/prelude_compiled.bc"))
        .unwrap_or_else(|e| panic!("src/prelude_compiled.bc unreadable ({}) — {}", e, REGEN));
    // Same reason as `bootstrap_prelude.rs`: the compile pipeline recurses far
    // past a default test thread's stack.
    let fresh = std::thread::Builder::new()
        .stack_size(64 * 1024 * 1024)
        .spawn(|| build_prelude_bitcode().expect("rebuilding the prelude bitcode failed"))
        .expect("failed to spawn the rebuild thread")
        .join()
        .expect("the rebuild thread panicked");
    assert_eq!(
        committed.len(),
        fresh.len(),
        "src/prelude_compiled.bc differs in length from a fresh build — {}",
        REGEN
    );
    assert!(committed == fresh, "src/prelude_compiled.bc differs from a fresh build — {}", REGEN);
}
