//! The committed prelude dump (`crates/typelisp-front/src/prelude.typld`) must
//! stay in sync with `prelude.rs`'s `SOURCE`. It is generated by
//! `scripts/regen-prelude-bitcode.sh` (the `typl-bootstrap-prelude` binary) and
//! consumed at startup by `prelude_bootstrap::load`.
//!
//! The same two guards, at the same two granularities, as
//! `island_artifacts_test.rs` — see that module's doc comment for why one is
//! not enough. The second matters more here: the prelude is compiled *by* the
//! compiler island, so this artifact goes stale when the island changes, and
//! the digest below covers only `prelude.rs`.

use typelisp::compile::llvm_context;
use typelisp::compile::prelude_bootstrap::build_prelude_artifact;
use typelisp::dump::{parse, read_state, sources_digest};

use inkwell::memory_buffer::MemoryBuffer;
use inkwell::module::Module;

const REGEN: &str = "run scripts/regen-prelude-bitcode.sh";
const DUMP: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/crates/typelisp-front/src/prelude.typld");

fn committed() -> Vec<u8> {
    std::fs::read(DUMP).unwrap_or_else(|e| panic!("{} unreadable ({}) — {}", DUMP, e, REGEN))
}

#[test]
fn prelude_artifacts_are_fresh() {
    let bytes = committed();
    let units = parse(&bytes, "prelude").unwrap_or_else(|e| panic!("{} — {}", e, REGEN));
    let unit = units.first().unwrap_or_else(|| panic!("the prelude dump holds no units — {}", REGEN));
    let state = read_state(unit.types, "prelude").unwrap_or_else(|e| panic!("{} — {}", e, REGEN));
    assert_eq!(
        state.source_digest,
        Some(sources_digest(typelisp::prelude::DUMPED_SOURCES)),
        "the prelude dump is stale relative to prelude.rs's SOURCE — {}",
        REGEN
    );

    // The bitcode half has to be parseable on its own: the loader hands LLVM
    // exactly this slice, so a directory that is off by a byte fails here
    // rather than at somebody's startup.
    let _guard = typelisp::compile::COMPILE_LOCK.lock().unwrap();
    let buffer = MemoryBuffer::create_from_memory_range_copy(unit.bitcode, "prelude");
    Module::parse_bitcode_from_buffer(&buffer, llvm_context())
        .unwrap_or_else(|_| panic!("the prelude dump's bitcode failed to parse — {}", REGEN));
}

/// The committed dump must be what building it *now* produces.
///
/// This is the guard that catches an island change: the prelude's bodies are
/// translated by `compiler.rs`'s `SOURCE` as compiled into the committed island
/// dump, plus the Rust-side LLVM builders — none of which the digest above
/// looks at. Comparing the output covers every input at once without having to
/// enumerate them.
///
/// Sound because the build is deterministic in the inputs and reads nothing
/// downstream of itself: unlike the island's generator, this one loads the
/// prelude *interpreted* and never installs the artifact it is replacing, so
/// building from the committed bytes and building from scratch are the same
/// computation. Byte equality also needs the checked-state half to serialize
/// reproducibly, which is why `dump`'s walk sorts every table and several
/// registry maps are `BTreeMap`s.
#[test]
fn the_committed_prelude_matches_a_fresh_build() {
    let committed = committed();
    // Same reason as `bootstrap_prelude.rs`: the compile pipeline recurses far
    // past a default test thread's stack.
    let fresh = std::thread::Builder::new()
        .stack_size(64 * 1024 * 1024)
        .spawn(|| build_prelude_artifact().expect("rebuilding the prelude dump failed"))
        .expect("failed to spawn the rebuild thread")
        .join()
        .expect("the rebuild thread panicked");
    assert_eq!(committed.len(), fresh.len(), "the prelude dump differs in length from a fresh build — {}", REGEN);
    assert!(committed == fresh, "the prelude dump differs from a fresh build — {}", REGEN);
}

/// The bitcode section carries the same load-bearing trailing NUL, for the
/// same reason — see `the_committed_island_keeps_its_trailing_nul` in
/// `island_artifacts_test.rs` for the writer/reader pairing and why the length
/// check is the one that actually catches a trim.
#[test]
fn the_committed_prelude_keeps_its_trailing_nul() {
    let bytes = committed();
    let units = parse(&bytes, "prelude").unwrap_or_else(|e| panic!("{} — {}", e, REGEN));
    let bc = units.first().expect("the prelude dump holds no units").bitcode;

    assert_eq!(&bc[..4], b"BC\xc0\xde", "the prelude dump's bitcode section is not LLVM bitcode at all");
    assert_eq!(
        bc.last().copied(),
        Some(0),
        "the prelude bitcode lost its trailing NUL — install_compiled_library asserts on it"
    );
    assert_eq!(
        (bc.len() - 1) % 4,
        0,
        "the prelude bitcode section is {} bytes; the bitstream proper must be a multiple of 4 \
         with exactly one NUL after it — {}",
        bc.len(),
        REGEN
    );
}
