#!/usr/bin/env bash
# Generates a machine-local `.cargo/config.toml` that pins
# `LLVM_SYS_170_PREFIX` to the Homebrew `llvm@17` toolchain, so a bare
# `cargo build`/`cargo test` links against LLVM 17 (what inkwell's `llvm17-0`
# feature expects) instead of whatever generic `llvm` the shell environment
# happens to point at.
#
# Why generate instead of commit: the prefix is machine-specific (Intel
# `/usr/local` vs Apple Silicon `/opt/homebrew`), so it must be resolved at
# setup time via `brew --prefix` and never hardcoded. The generated
# `.cargo/config.toml` is git-ignored.
#
# Run once after cloning:
#   scripts/setup-cargo-env.sh
#
# On macOS the minimum OS version is read from the toolchain's std. When that
# cannot be read, the script says so and stops; choose the value yourself with
#   scripts/setup-cargo-env.sh --deployment-target <version>
#
# `scripts/with-llvm-env.sh cargo ...` remains available and needs no setup.
set -euo pipefail

usage="usage: scripts/setup-cargo-env.sh [--deployment-target <version>]"
chosen=""
while [ $# -gt 0 ]; do
    case "$1" in
        --deployment-target) [ $# -ge 2 ] || { echo "$usage" >&2; exit 1; }; chosen="$2"; shift 2 ;;
        --deployment-target=*) chosen="${1#--deployment-target=}"; shift ;;
        *) echo "$usage" >&2; exit 1 ;;
    esac
done
if [ -n "$chosen" ]; then
    if [ "$(uname -s)" != Darwin ]; then
        echo "error: --deployment-target is for macOS; this is $(uname -s)" >&2
        exit 1
    fi
    if ! [[ "$chosen" =~ ^[0-9]+(\.[0-9]+){0,2}$ ]]; then
        echo "error: --deployment-target \`$chosen\` is not a version like 15.0" >&2
        exit 1
    fi
fi

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if ! command -v brew >/dev/null 2>&1; then
    echo "error: brew not found; install LLVM 17 and set LLVM_SYS_170_PREFIX yourself" >&2
    exit 1
fi

prefix="$(brew --prefix llvm@17)"
if [ ! -x "$prefix/bin/llvm-config" ]; then
    echo "error: llvm@17 not found at $prefix; run 'brew install llvm@17'" >&2
    exit 1
fi

# macOS: one minimum OS version for rustc, the `cc` crate (ring) and
# `compile-file`'s link, the one the toolchain's std was built for — see
# build.rs and scripts/macos-deployment-target.sh. Re-run this script after
# changing the Rust toolchain.
deployment=""
if [ -n "$chosen" ]; then
    deployment="$chosen"
elif [ "$(uname -s)" = Darwin ]; then
    deployment="$("$repo_root/scripts/macos-deployment-target.sh")"
fi

mkdir -p "$repo_root/.cargo"
cat > "$repo_root/.cargo/config.toml" <<EOF
# Generated by scripts/setup-cargo-env.sh — do not commit (git-ignored).
# Pins the LLVM 17 prefix (and, on macOS, the minimum OS version) so bare
# cargo commands link correctly.
[env]
LLVM_SYS_170_PREFIX = { value = "$prefix", force = true }
EOF
if [ -n "$deployment" ]; then
    echo "MACOSX_DEPLOYMENT_TARGET = { value = \"$deployment\", force = true }" >> "$repo_root/.cargo/config.toml"
fi

echo "wrote $repo_root/.cargo/config.toml (LLVM_SYS_170_PREFIX=$prefix${deployment:+, MACOSX_DEPLOYMENT_TARGET=$deployment})"
