#!/usr/bin/env bash
# Generates a machine-local `.cargo/config.toml` that pins
# `LLVM_SYS_170_PREFIX` to the Homebrew `llvm@17` toolchain, so a bare
# `cargo build`/`cargo test` links against LLVM 17 (what inkwell's `llvm17-0`
# feature expects) instead of whatever generic `llvm` the shell environment
# happens to point at.
#
# Why generate instead of commit: the prefix is machine-specific (Intel
# `/usr/local` vs Apple Silicon `/opt/homebrew`), so it must be resolved at
# setup time via `brew --prefix` and never hardcoded. The generated
# `.cargo/config.toml` is git-ignored.
#
# Run once after cloning:
#   scripts/setup-cargo-env.sh
#
# `scripts/with-llvm-env.sh cargo ...` remains available and needs no setup.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if ! command -v brew >/dev/null 2>&1; then
    echo "error: brew not found; install LLVM 17 and set LLVM_SYS_170_PREFIX yourself" >&2
    exit 1
fi

prefix="$(brew --prefix llvm@17)"
if [ ! -x "$prefix/bin/llvm-config" ]; then
    echo "error: llvm@17 not found at $prefix; run 'brew install llvm@17'" >&2
    exit 1
fi

mkdir -p "$repo_root/.cargo"
cat > "$repo_root/.cargo/config.toml" <<EOF
# Generated by scripts/setup-cargo-env.sh — do not commit (git-ignored).
# Pins the LLVM 17 prefix so bare cargo commands link correctly.
[env]
LLVM_SYS_170_PREFIX = { value = "$prefix", force = true }
EOF

echo "wrote $repo_root/.cargo/config.toml (LLVM_SYS_170_PREFIX=$prefix)"
